---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-configs
  namespace: code-server
  labels:
    app: code-server
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: localhost
---
apiVersion: v1
kind: Secret
metadata:
  name: code-server-configs
  namespace: code-server
  labels:
    app: code-server
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=
