---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server
  namespace: code-server
  labels:
    app: code-server
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  volumeName: code-server
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
