version: '3'

volumes:
    northwind-db:

networks:
    mynet:

services:
    myapp:
        image: stackupiss/northwind-app:v1
        networks:
            - mynet
        ports:
            - 8080:3000
        environment:
            - DB_HOST=mydb
            - DB_USER=root
            - DB_PASSWORD=changeit

    mydb:
        image: stackupiss/northwind-db:v1
        networks:
            - mynet
        depends_on:
            - myapp
        volumes:
            - northwind-db:/var/lib/mysql
