apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"env":"dev"},"name":"minio"}}
    labels:
      env: dev
    name: minio
- apiVersion: v1
  data:
    MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=
    MINIO_ROOT_USER: dXNlcg==
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"MINIO_ROOT_PASSWORD":"cGFzc3dvcmQ=","MINIO_ROOT_USER":"dXNlcg=="},"kind":"Secret","metadata":{"annotations":{},"labels":{"env":"dev"},"name":"devminio-config-g4hkc6d4tt","namespace":"minio"},"type":"Opaque"}
    labels:
      env: dev
    name: devminio-config-g4hkc6d4tt
    namespace: minio
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"minio","env":"dev"},"name":"devminio-headless","namespace":"minio"},"spec":{"ports":[{"port":9000,"targetPort":9000},{"port":9090,"targetPort":9090}],"selector":{"app":"minio-headless","env":"dev"}}}
    labels:
      app: minio
      env: dev
    name: devminio-headless
    namespace: minio
  spec:
    ports:
    - port: 9000
      targetPort: 9000
    - port: 9090
      targetPort: 9090
    selector:
      app: minio-headless
      env: dev
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"minio","env":"dev"},"name":"devminio","namespace":"minio"},"spec":{"replicas":4,"selector":{"matchLabels":{"app":"minio","env":"dev"}},"serviceName":"devminio-headless","template":{"metadata":{"labels":{"app":"minio","env":"dev"}},"spec":{"containers":[{"args":["--address=:9000","--console-address=:9090","http://minio{0...3}.minio-headless.minio.svc.cluster.local/data"],"command":["minio","server"],"envFrom":[{"secretRef":{"name":"devminio-config-g4hkc6d4tt"}}],"image":"bitnami/minio@sha256:63fd32b5fdbedc7cf7252e0420f4402c9da95c3268b2e894b7cd6f71889931f0","livenessProbe":{"httpGet":{"path":"/minio/health/live","port":900},"initialDelaySeconds":60,"timeoutSeconds":10},"name":"minio","ports":[{"containerPort":9000,"name":"data"},{"containerPort":9090,"name":"data"}],"readinessProbe":{"httpGet":{"path":"/minio/health/ready","port":900},"initialDelaySeconds":60,"timeoutSeconds":10},"resources":{"limits":{"cpu":"200m","memory":"250Mb"}},"volumeMounts":[{"mountPath":"/data","name":"data-vol"}]}]}},"volumeClaimTemplates":[{"metadata":{"consumed-by":"minio","labels":{"env":"dev"},"name":"data-vol"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}]}}
    labels:
      app: minio
      env: dev
    name: devminio
    namespace: minio
  spec:
    replicas: 4
    selector:
      matchLabels:
        app: minio
        env: dev
    serviceName: devminio-headless
    template:
      metadata:
        labels:
          app: minio
          env: dev
      spec:
        containers:
        - args:
          - --address=:9000
          - --console-address=:9090
          - http://minio{0...3}.minio-headless.minio.svc.cluster.local/data
          command:
          - minio
          - server
          envFrom:
          - secretRef:
              name: devminio-config-g4hkc6d4tt
          image: bitnami/minio@sha256:63fd32b5fdbedc7cf7252e0420f4402c9da95c3268b2e894b7cd6f71889931f0
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 900
            initialDelaySeconds: 60
            timeoutSeconds: 10
          name: minio
          ports:
          - containerPort: 9000
            name: data
          - containerPort: 9090
            name: data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 900
            initialDelaySeconds: 60
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 250Mb
          volumeMounts:
          - mountPath: /data
            name: data-vol
    volumeClaimTemplates:
    - metadata:
        consumed-by: minio
        labels:
          env: dev
        name: data-vol
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
kind: List
metadata: {}
