---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-configs
  namespace: code-server
  labels:
    app: code-server
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-130.16.2.33.nip.io
