---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: code-server
  labels:
    app: code-server
spec:
  selector:
    app: code-server
  ports:
    - port: 8443
      targetPort: app-port
      name: app-port
