---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  env: dev

namePrefix: dev-
nameSuffix: -test

generatorOptions:
  labels:
    env: dev

configMapGenerator:
  - name: code-server-configs
    behavior: merge
    namespace: code-server
    literals:
      - PROXY_DOMAIN="localhost"

patches:
  - target:
      version: v1
      group: networking.k8s.io
      kind: Ingress
      name: code-server
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: localhost
