---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: minio

commonLabels:
  env: dev

secretGenerator:
  - name: minio-config
    behavior: create
    namespace: minio
    literals:
      - MINIO_ROOT_USER="user"
      - MINIO_ROOT_PASSWORD="password"
